name: Create Release PR

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-pr:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'release/')
    steps:
      - uses: googleapis/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          skip-github-release: true
          pull-request-title-pattern: 'chore: release ${version}'
          default-branch: ${{ github.ref_name }}
